name: MLOps CI
on: [push]

env:
  REGION: europe-west2

jobs:
  build-test-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ci-cd-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - run: pip install -r requirements.txt
    # - run: pytest
    - run: python pipelines/submit_pipeline.py